version: '3'
services:
  backend:
    image: node:12.16.1-alpine
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - rchat
    command: /bin/sh -c "cd /app && npm run start-dev"
    env_file:
      - .env
  mysql:
    image: mariadb
    restart: always
    volumes:
      - ./database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rchat
      MYSQL_ROOT_PASSWORD: rchat123
    networks:
      - rchat
networks:
  rchat: